---
name: HideCommands
version: 2.0.0
main: Himbeer\HideCommands\Main
api: 4.0.0

author: Himbeer
website: himbeer.me
description: Remove specific commands from the in-game command suggestions.

permissions:
  hidecommands:
    default: false
  hidecommands.unhide:
    description: "Players with this permission can see all commands"
    default: false
...
